### ISSUE TITLE
Update for PHP 8.1 & 8.2

### ISSUE THREAD

**Issue by nicolas-grekas** [jakzal/docker-symfony-intl#24]
Hello @jakzal 

I tried running an update on Symfony but it failed because I was on branch 6.3 and this one requires PHP 8.1 :grimacing: 

:pray:

**Comment by jakzal** [comment]
I added PHP 8.1, 8.2, and the most recent ICU versions. 

https://github.com/jakzal/docker-symfony-intl/blob/0b8e66634c4984db3fdb39e789b393ab746cfa12/.github/workflows/build.yml#L16-L18

Pushed to [docker hub](https://hub.docker.com/repository/docker/jakzal/php-intl/tags?page=1&ordering=last_updated).

```
$ curl -Ls 'https://registry.hub.docker.com/v2/repositories/jakzal/php-intl/tags?page_size=20' | jq '.results[].name' --raw-output | sort
7.4-66.1
7.4-67.1
8.0-66.1
8.0-67.1
8.0-68.2
8.0-69.1
8.0-70.1
8.0-71.1
8.1-66.1
8.1-67.1
8.1-68.2
8.1-69.1
8.1-70.1
8.1-71.1
8.2-66.1
8.2-67.1
8.2-68.2
8.2-69.1
8.2-70.1
8.2-71.1
```
